# Generated by Django 5.1.4 on 2024-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Meeting Room', 'Meeting Room'), ('Auditorium', 'Auditorium'), ('Office', 'Office')], max_length=20),
        ),
    ]
