# Generated by Django 5.1.4 on 2024-12-17 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_quotation_booking_type_quotation_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='final_price_with_gst',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
