# Generated by Django 5.1.4 on 2024-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_enquiry_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='room_type',
            field=models.CharField(choices=[('Meeting Room', 'Meeting Room'), ('Auditorium', 'Auditorium'), ('Office', 'Office')], max_length=20),
        ),
    ]
